### ISSUE TITLE
Wiring setup

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [9SQ/esp8266-wifi-setup#1]
Hi @9SQ !

Can you share a wiring setup for your code?

Thanks! :)

**Comment by 9SQ** [comment]
Hi @arkadiusz-wieczorek ,

I added wiring information at the README.md

Please check this!

[https://github.com/9SQ/esp8266-wifi-setup#wiring](https://github.com/9SQ/esp8266-wifi-setup#wiring)

**Comment by arkadiusz-wieczorek** [comment]
Hi @9SQ,

thank you!
